#!/bin/sh


echo "Starting ADB..."

modprobe atc260x_cap_gauge
modprobe gpio_keys_polled
modprobe g_cdc
modprobe usb_f_acm
modprobe g_android
modprobe u_serial
modprobe ethernet

echo 0 > /sys/monitor/usb_port/config/run

# host -> device
echo 1 > /sys/monitor/usb_port/config/idpin_debug
/usbmond.sh USB_A_OUT && /usbmond.sh USB_B_IN

